name: ZEBRADOG - Demo 
markdown: redcarpet
exclude: ["CNAME","README.md","LICENSE"]
permalink: /:title/
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
gems:
  - jekyll-redirect-from
prose:
	rooturl: "_posts"
	siteurl: "http://demo.zebradog.com/"
	metadata:
		_posts:
			- name: "categories"
					field:
						element: "multiselect"
						value: "featured"
						options: ["featured","digital signage","interactive kiosks","dynamic media installations"]
