name: ZEBRADOG - Demo 
markdown: redcarpet
exclude: 
  - "CNAME"
  - "README.md"
  - "LICENSE"
permalink: /:title/
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
gems:
  - jekyll-redirect-from
prose:
  rooturl: '_posts'
  siteurl: 'http://demo.zebradog.com/'
  media: '_posts/media'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "demo"
        field:
          element: "text"
          label: "Demo URL"
      - name: "vimeo"
        field:
          element: "text"
          label: "Vimeo Video ID"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          value: "featured"
          options: 
            - "featured"
            - "digital signage"
            - "interactive kiosks"
            - "dynamic media installations"
